import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


import "../public/css/blue-color.css";

import "../public/css/bootstrap.min.css";
import "../public/css/font-awesome.css";
import "../public/css/owl.carousel.css";
import "../public/css/owl.carousel.css";
import "../public/css/owl.transitions.css";
import "../public/css/settings.css";
import "../public/css/layers.css";
import "../public/css/navigation.css";
import "../public/css/style.css";
import "../public/css/animate.css";
import "../public/css/owl.transitions.css";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <script src="js/wow.js"></script> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
